# This is a basic workflow to help you get started with Actions

name: Build Projects

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.x'
  ELECTRON_DOTNET_VERSION: '6.0.x'
  CLI_PROJECT_PATH: HybridConnectionManagerCLI/HybridConnectionManagerCLI.csproj
  GUI_PROJECT_PATH: HybridConnectionManagerGUI/HybridConnectionManagerGUI.csproj
  SERVICE_PROJECT_PATH: HybridConnectionManagerService/HybridConnectionManagerService.csproj
  INSTALLER_PROJECT_DIR: HybridConnectionManagerService/HybridConnectionManagerService.csproj



# Controls when the workflow will run
on:
  # Triggers the workflow on push to "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
      id-token: write
      contents: read

jobs:
 
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
              ${{ env.DOTNET_VERSION }}
              ${{ env.ELECTRON_DOTNET_VERSION }}

      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g

      - name: Install WixTools
        run: dotnet tool install wix -g --version 5.0.2

      - name: Publish CLI for Windows
        run: dotnet publish ${{ env.CLI_PROJECT_PATH }} -r win-x64 -p:PublishSingleFile=true -p:WarningLevel=0

      - name: Publish Windows Electron App for GUI
        working-directory: HybridConnectionManagerGUI
        run: electronize build /target win /property:WarningLevel=0

      - name: Publish Service for Windows
        run: dotnet publish ${{ env.SERVICE_PROJECT_PATH }} -r win-x64 -p:PublishSingleFile=true -p:WarningLevel=0

      - name: Build Windows Installer
        working-directory: HybridConnectionManagerWindowsInstaller
        run: dotnet build -c Release -p:WarningLevel=0

      - name: Upload Windows Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows installer
          path: ${{ env.INSTALLER_PROJECT_DIR }}/bin/Release/HybridConnectionManagerV2.msi
          retention-days: 1