# This is a basic workflow to help you get started with Actions

name: Build Projects

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.x'
  CLI_SOLUTION_PATH: HybridConnectionManagerCLI/HybridConnectionManagerCLI.sln
  FUNCTION_SOLUTION_PATH: src/Function/Function.sln

# Controls when the workflow will run
on:
  # Triggers the workflow on push to "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
      id-token: write
      contents: read

jobs:
 
  build-CLI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build CLI with dotnet
        run: dotnet build ${{ env.CLI_SOLUTION_PATH }} --configuration Release

      - name: Publish CLI for Windows
        run: dotnet publish ${{ env.CLI_SOLUTION_PATH }} -r win-x64 -p:PublishSingleFile=true -o ${{env.DOTNET_ROOT}}/cli/win

      - name: Publish CLI for Linux
        run: dotnet publish ${{ env.CLI_SOLUTION_PATH }} -r linux-x64 -p:PublishSingleFile=true -o ${{env.DOTNET_ROOT}}/cli/linux

      - name: Upload Windows CLI artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-cli
          path: ${{env.DOTNET_ROOT}}/cli/win
          retention-days: 1

      - name: Upload Linux CLI artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-app
          path: ${{env.DOTNET_ROOT}}/cli/linux
          retention-days: 1