# This is a basic workflow to help you get started with Actions

name: Build Projects

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.x'
  CLI_PROJECT_PATH: HybridConnectionManagerCLI/HybridConnectionManagerCLI.csproj
  GUI_PROJECT_PATH: HybridConnectionManagerGUI/HybridConnectionManagerGUI.csproj
  SERVICE_PROJECT_PATH: HybridConnectionManagerService/HybridConnectionManagerService.csproj


# Controls when the workflow will run
on:
  # Triggers the workflow on push to "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
      id-token: write
      contents: read

jobs:
 
  build-CLI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build CLI with dotnet
        run: dotnet build ${{ env.CLI_PROJECT_PATH }} --configuration Release

      - name: Publish CLI for Windows
        run: dotnet publish ${{ env.CLI_PROJECT_PATH }} -r win-x64 -p:PublishSingleFile=true -o ${{env.DOTNET_ROOT}}/cli/win

      - name: Publish CLI for Linux
        run: dotnet publish ${{ env.CLI_PROJECT_PATH }} -r linux-x64 -p:PublishSingleFile=true -o ${{env.DOTNET_ROOT}}/cli/linux

      - name: Upload Windows CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-cli
          path: ${{env.DOTNET_ROOT}}/cli/win
          retention-days: 1

      - name: Upload Linux CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: ${{env.DOTNET_ROOT}}/cli/linux
          retention-days: 1

  build-GUI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build GUI with dotnet
        run: dotnet build ${{ env.GUI_PROJECT_PATH }} --configuration Release

      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g

      - name: Publish Windows Electron App for GUI
        run: electronize build /target win /absolute-path ${{env.DOTNET_ROOT}}/gui/win

      - name: Publish Linux Electron App for GUI
        run: electronize build /target linux /absolute-path ${{env.DOTNET_ROOT}}/gui/linux

      - name: Upload Windows GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-gui
          path: ${{env.DOTNET_ROOT}}/gui/win
          retention-days: 1

      - name: Upload Linux GUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-gui
          path: ${{env.DOTNET_ROOT}}/gui/linux
          retention-days: 1